/**
 * Pact provider verification — issue #791
 *
 * Starts a minimal Express server on an ephemeral port and runs the Pact
 * Verifier against the contracts generated by the consumer (frontend).
 *
 * State handlers use a shared in-memory store so each interaction gets the
 * right fixture response without hitting Soroban RPC, Horizon, or a database.
 *
 * Run:
 *   npm run test:pact
 */

import http from "http";
import { describe, it, beforeAll, afterAll } from "vitest";
import { Verifier } from "@pact-foundation/pact";
import path from "path";
import { fileURLToPath } from "url";
import express from "express";
import type { Request, Response, NextFunction } from "express";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// ── Shared mutable state injected by Pact state handlers ─────────────────────

interface AppState {
  schedule: Record<string, unknown> | null;
  notFound: boolean;
  sponsorItems: unknown[];
  txResult: Record<string, unknown> | null;
}

const appState: AppState = {
  schedule: null,
  notFound: false,
  sponsorItems: [],
  txResult: null,
};

function resetState() {
  appState.schedule = null;
  appState.notFound = false;
  appState.sponsorItems = [];
  appState.txResult = null;
}

// ── Minimal Express app ───────────────────────────────────────────────────────

function buildApp() {
  const app = express();
  app.use(express.json());

  // GET /api/schedules/:recipient
  app.get("/api/schedules/:recipient", (req: Request, res: Response) => {
    if (appState.notFound) {
      res.status(404).json({ error: "schedule not found" });
      return;
    }
    if (appState.schedule) {
      res.json({ ...appState.schedule, recipient: req.params.recipient });
      return;
    }
    res.status(404).json({ error: "schedule not found" });
  });

  // GET /api/schedules/sponsor/:sponsor
  // Note: Express matches more-specific paths first, so the literal segment
  // "sponsor" takes priority over :recipient only if we define it first.
  // We need to guard against /schedules/sponsor/:sponsor matching :recipient.
  app.get("/api/schedules/sponsor/:sponsor", (req: Request, res: Response) => {
    const page = parseInt((req.query.page as string) ?? "1", 10);
    const limit = parseInt((req.query.limit as string) ?? "20", 10);
    res.json({
      items: appState.sponsorItems,
      page,
      limit,
      next_cursor: null,
    });
  });

  // POST /api/tx/submit
  app.post("/api/tx/submit", (req: Request, res: Response) => {
    if (appState.txResult) {
      res.json(appState.txResult);
      return;
    }
    res.status(500).json({ error: "no state configured" });
  });

  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  app.use((err: Error, _req: Request, res: Response, _next: NextFunction) => {
    res.status(500).json({ error: err.message });
  });

  return app;
}

// ── Server lifecycle ──────────────────────────────────────────────────────────

let server: http.Server;
let providerPort: number;

beforeAll(
  () =>
    new Promise<void>((resolve) => {
      const app = buildApp();
      server = http.createServer(app);
      server.listen(0, "127.0.0.1", () => {
        const addr = server.address() as { port: number };
        providerPort = addr.port;
        resolve();
      });
    }),
);

afterAll(
  () =>
    new Promise<void>((resolve, reject) => {
      server.close((err) => (err ? reject(err) : resolve()));
    }),
);

// ── Pact verifier ─────────────────────────────────────────────────────────────

describe("Pact provider verification — vesting-backend", () => {
  it("satisfies all consumer contracts", async () => {
    const pactBrokerUrl = process.env.PACT_BROKER_URL;
    const pactDir = path.resolve(__dirname, "../../../pacts");
    const pactFile = path.join(pactDir, "vesting-frontend-vesting-backend.json");

    /** Build the pact source: broker in CI, local file locally. */
    const pactSource =
      pactBrokerUrl && process.env.CI
        ? {
            pactBrokerUrl,
            ...(process.env.PACT_BROKER_TOKEN
              ? { pactBrokerToken: process.env.PACT_BROKER_TOKEN }
              : {
                  pactBrokerUsername: process.env.PACT_BROKER_USERNAME ?? "pact_workshop",
                  pactBrokerPassword: process.env.PACT_BROKER_PASSWORD ?? "pact_workshop",
                }),
            consumerVersionSelectors: [
              { mainBranch: true },
              { deployedOrReleased: true },
              {
                branch:
                  process.env.GITHUB_HEAD_REF ??
                  process.env.GITHUB_REF_NAME ??
                  "main",
              },
            ],
          }
        : { pactUrls: [pactFile] };

    const verifier = new Verifier({
      provider: "vesting-backend",
      providerBaseUrl: `http://127.0.0.1:${providerPort}`,

      // State handlers — called before each interaction.
      // They mutate `appState` which the Express handlers read.
      stateHandlers: {
        "a vesting schedule exists for recipient": async () => {
          resetState();
          appState.schedule = {
            sponsor: "GSPON1EXAMPLESPONSORADDRESSXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
            token: "CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHK3M",
            rate: "100",
            cliff_ledger: 51_200_000,
            end_ledger: 51_800_000,
            start_ledger: 51_000_000,
            claimable_amount: "5000",
            is_cliff_passed: true,
          };
        },

        "no vesting schedule exists for recipient": async () => {
          resetState();
          appState.notFound = true;
        },

        "streams exist for sponsor": async () => {
          resetState();
          appState.sponsorItems = [
            {
              recipient: "GABC1EXAMPLERECIPIENTADDRESSXXXXXXXXXXXXXXXXXXXXXXXXXXX",
              sponsor: "GSPON1EXAMPLESPONSORADDRESSXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
              token: "CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHK3M",
              ledger: 51_000_000,
              event_id: "0000000000000000",
            },
          ];
        },

        "backend is configured with a valid signing key and contract": async () => {
          resetState();
          appState.txResult = {
            hash: "a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2",
            status: "SUCCESS",
          };
        },
      },

      ...pactSource,

      // Publish verification results back to broker in CI
      publishVerificationResult: Boolean(process.env.CI && pactBrokerUrl),
      providerVersion: process.env.GITHUB_SHA ?? "local",
      providerVersionBranch: process.env.GITHUB_REF_NAME ?? "local",
      logLevel: "warn",
    });

    await verifier.verifyProvider();
  }, 60_000);
});
