#!/usr/bin/env bash
# scripts/fund_accounts.sh
#
# Generates and funds test key pairs for integration tests against a local
# Stellar quickstart node. Uses the Friendbot endpoint to fund each account.
#
# Generated keys are stored in the Stellar CLI keystore under the names
# defined in $KEY_NAMES. The public addresses are exported as environment
# variables and also written to .integration_accounts (sourced by tests).
#
# Usage:
#   source scripts/fund_accounts.sh
#   echo "Sponsor: $SPONSOR_ADDRESS"
#
# Environment variables (all optional):
#   HORIZON_URL        — Horizon URL (default: http://localhost:8000)
#   STELLAR_NETWORK    — network name (default: local)
#   RPC_URL            — Soroban RPC URL (default: http://localhost:8000/soroban/rpc)

set -euo pipefail

HORIZON_URL="${HORIZON_URL:-http://localhost:8000}"
STELLAR_NETWORK="${STELLAR_NETWORK:-local}"
RPC_URL="${RPC_URL:-http://localhost:8000/soroban/rpc}"

ACCOUNTS_FILE=".integration_accounts"

log() { echo "[fund_accounts] $*" >&2; }

fund_account() {
  local key_name="$1"
  # Generate key pair if it doesn't exist
  if ! stellar keys address "$key_name" &>/dev/null; then
    log "Generating key pair: $key_name"
    stellar keys generate "$key_name" --network "$STELLAR_NETWORK" --rpc-url "$RPC_URL" 2>/dev/null
  else
    log "Key pair '$key_name' already exists."
  fi

  local address
  address=$(stellar keys address "$key_name" 2>/dev/null)

  # Fund via Friendbot (local quickstart node)
  log "Funding $key_name ($address)..."
  curl -sf "${HORIZON_URL}/friendbot?addr=${address}" -o /dev/null \
    || log "  (Friendbot may already have funded this account)"

  echo "$address"
}

# ── Generate and fund all test accounts ───────────────────────────────────────

DEPLOYER_ADDRESS=$(fund_account "integration-deployer")
ADMIN_ADDRESS=$(fund_account "integration-admin")
TREASURY_ADDRESS=$(fund_account "integration-treasury")
SPONSOR_ADDRESS=$(fund_account "integration-sponsor")
RECIPIENT_ADDRESS=$(fund_account "integration-recipient")
SPONSOR2_ADDRESS=$(fund_account "integration-sponsor2")
RECIPIENT2_ADDRESS=$(fund_account "integration-recipient2")
CALLER_ADDRESS=$(fund_account "integration-caller")

# ── Write addresses to file (sourced by test scripts) ─────────────────────────

cat > "$ACCOUNTS_FILE" <<EOF
# Generated by scripts/fund_accounts.sh — do not edit manually.
DEPLOYER_ADDRESS="$DEPLOYER_ADDRESS"
ADMIN_ADDRESS="$ADMIN_ADDRESS"
TREASURY_ADDRESS="$TREASURY_ADDRESS"
SPONSOR_ADDRESS="$SPONSOR_ADDRESS"
RECIPIENT_ADDRESS="$RECIPIENT_ADDRESS"
SPONSOR2_ADDRESS="$SPONSOR2_ADDRESS"
RECIPIENT2_ADDRESS="$RECIPIENT2_ADDRESS"
CALLER_ADDRESS="$CALLER_ADDRESS"
EOF

log "Account addresses written to $ACCOUNTS_FILE"

# Export for callers who source this script
export DEPLOYER_ADDRESS ADMIN_ADDRESS TREASURY_ADDRESS
export SPONSOR_ADDRESS RECIPIENT_ADDRESS
export SPONSOR2_ADDRESS RECIPIENT2_ADDRESS CALLER_ADDRESS
